### ISSUE TITLE
Error generating final archive: Found duplicate file for APK: project.properties

### ISSUE THREAD

**Issue by pangminfu** [clkasd/CarouselViewProject#1]
I'm getting this error an unable to build the project. can i get the complete source code project to generate the jar file myself?

**Comment by clkasd** [comment]
Well it is complete source code project.Just download and open in eclipse.I tried myself just now and everything looks ok.But if you need a .jar of it ,I have exported. You can download from here : https://www.dropbox.com/s/dsucgkirh3h1zun/carouselView.jar?dl=0
