### ISSUE TITLE
Next and previous cards are over lapping

### ISSUE THREAD

**Issue by SureshSc** [clkasd/CarouselViewProject#5]
@clkasd  When i change the Page margin and the angle for previous and next card unfortunately its overlapping(i.e centre card goes behind the next card). How to bring it to the front?

refer my question 
http://stackoverflow.com/questions/32606524/view-in-the-view-pager-overlap-between-previous-and-next-view

**Comment by clkasd** [comment]
I believe you found solution for your issue with using view.bringToFront();
